import { FaArrowLeft } from "react-icons/fa";

export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main>
      <nav className="grid grid-cols-3">
        <div>
          <FaArrowLeft size={20} />
        </div>
        <div>Tittle</div>
      </nav>
      {children}
    </main>
  );
}
