export const transactions = [
  {
    id: 1,
    date: "2025-05-01",
    type: "income",
    amount: 5000000,
    category: { key: "salary", name: "Gaji" },
    description: "Gaji pokok bulan Mei",
  },
  {
    id: 2,
    date: "2025-05-02",
    type: "expense",
    amount: 75000,
    category: { key: "food", name: "Makan" },
    description: "Makan siang di restoran",
  },
  {
    id: 3,
    date: "2025-05-05",
    type: "expense",
    amount: 300000,
    category: { key: "shopping", name: "Belanja" },
    description: "Beli bahan makanan mingguan",
  },
  {
    id: 4,
    date: "2025-05-07",
    type: "income",
    amount: 200000,
    category: { key: "bonus", name: "Bonus" },
    description: "Bonus proyek freelance",
  },
  {
    id: 5,
    date: "2025-05-08",
    type: "expense",
    amount: 120000,
    category: { key: "transport", name: "Transportasi" },
    description: "Bensin mobil",
  },
  {
    id: 6,
    date: "2025-05-09",
    type: "income",
    amount: 750000,
    category: { key: "sales", name: "Penjualan" },
    description: "Penjualan barang bekas",
  },
];
